- hosts: 192.168.122.101
  remote_user: root
  gather_facts: no
  tasks:
  - name: add host name
    add_host:
      name: 183.131.18.163
      ansible_ssh_pass: "123"
      ansible_ssh_user: root
      ansible_ssh_port: 2121
- hosts: 183.131.18.163
  remote_user: root
  tasks:
  - name: test new host
    debug:
      msg: "{{ansible_os_family}}"
