---
- hosts: 192.168.122.101
  remote_user: root
  gather_facts: no
  tasks:
  - name: compressed dir
    archive:
      path:
      - /tmp/test*
      remove: yes
      exclude_path: /tmp/test2
      dest: /tmp/tar/test.tar.gz
      format: gz
